# Agency config
DEFAULT_PREFIX_HEADSIGNS = False
DEFAULT_ACCURATE_SECONDS = True
DEFAULT_PREFER_ROUTE_ID = False
DEFAULT_PREFER_STOP_ID = False
DEFAULT_SHOW_STOP_NUMBER = True
DEFAULT_VEHICLE_NAME_LENGTH = None
DEFAULT_DISTANCE_SCALE = 1
