
import pytz

# Agency config
DEFAULT_ACCURATE_SECONDS = True
DEFAULT_DISTANCE_SCALE = 1
DEFAULT_ENABLE_BLOCKS = True
DEFAULT_ENABLE_OCCUPANCY = True
DEFAULT_ENABLE_ROUTE_VARIANTS = True
DEFAULT_ENABLE_STACKED_HEADSIGNS = False
DEFAULT_FILTER_VEHICLES_IMAGE_NAME = 'bus'
DEFAULT_NIS_COLOUR = '989898'
DEFAULT_PREFER_ROUTE_ID = False
DEFAULT_PREFER_STOP_ID = False
DEFAULT_PREFIX_HEADSIGNS = False
DEFAULT_ROUTE_COLOUR = None
DEFAULT_SHOW_FULL_ORDERS = False
DEFAULT_SHOW_STOP_NUMBER = True
DEFAULT_VEHICLE_NAME_LENGTH = None
DEFAULT_VEHICLE_TYPE = 'Bus'
DEFAULT_VEHICLE_TYPE_PLURAL = 'Buses'

# System config
DEFAULT_ENABLE_FORCE_GTFS = True
DEFAULT_GTFS_CUTOFF = None
DEFAULT_IGNORE_ROUTE_COLOUR = None
DEFAULT_MAX_INVALID_POSITIONS = 0

# Date/time config
DEFAULT_TIMEZONE = pytz.timezone('America/Vancouver')

# Logging config
DEFAULT_ADMIN_LOGS_COUNT = 2000
